""" AMSR KiCAD Tools"""

import os
import uuid
from pathlib import Path

import jinja2

import asmr.design.gfx


DIR_PATH = os.path.dirname(os.path.realpath(__file__))
FOOTPRINT_EXT = 'kicad_mod'
FOOTPRINT_TEMPLATE = Path(f'{DIR_PATH}/templates/footprint.{FOOTPRINT_EXT}.jinja')

def render_template(output_filename, template, context):
    with open(template, 'r') as fd:
        t = jinja2.Template(fd.read())
    t.stream(**context).dump(str(Path.cwd()/output_filename))

class Line:
    def __init__(self,
                 x0,
                 y0,
                 x1,
                 y1,
                 width,
                 layer="F.SilkS"):
        self.uuid = uuid.uuid4()
        self.x0 = x0
        self.y0 = y0
        self.x1 = x1
        self.y1 = y1
        self.width = width
        self.layer = layer

    @staticmethod
    def from_gfx_line(line, layer="F.SilkS", offset=(0, 0)):
        return Line(
            line.x0 - offset[0],
            line.y0 - offset[1],
            line.x1 - offset[0],
            line.y1 - offset[1],
            line.width,
            layer=layer,
        )

class FpPad:
    def __init__(self, id):
        self.id = id
        self.uuid = uuid.uuid4()
        self.type = 'smd'
        self.shape = 'custom'
        self.lines = []
        self.x = 0
        self.y = 0

    def add_line(self, line):
        if len(self.lines) == 0:
            self.x = line.x0
            self.y = line.y0
        self.lines.append(Line.from_gfx_line(line, layer="F.Cu", offset=(self.x, self.y)))
        self.width = self.lines[-1].width

class Footprint:
    def __init__(self,
                 filename,
                 pads=[],
                 mask=[],
                 silkscreen=[]):
        self.filename = filename
        self.pads = {}
        self.masks = {}
        self.silkscreens = {}
        if len(pads) > 0:
            self.pads_from_shapes(pads)
        if len(mask) > 0:
            self.mask_from_shapes(mask)
        if len(silkscreen) > 0:
            self.silkscreen_from_shapes(silkscreen)

    def pads_from_shapes(self, shapes):
        for shape in shapes:
            pad_id = shape.group.split("=")[-1]

            if pad_id in self.pads:
                pad = self.pads[pad_id]
            else:
                pad = FpPad(pad_id)
                self.pads[pad_id] = pad

            if shape.__class__ == asmr.design.gfx.Line:
                pad.add_line(shape)


    def mask_from_shapes(self, shapes):
        # TODO implement me
        pass

    def silkscreen_from_shapes(self, shapes):
        # TODO implement me
        pass

    def save(self):
        name = '.'.join(self.filename.split('.')[:-1])
        # TODO pass masks and silkscreens into here
        ctx = {
            'footprint_name': f'{name}',
            'date_created': '20230303',
            'generating_program': 'asmr',
            'description': 'a footprint generated by asmr toolkit.',
            'canonical_layer': 'F.Cu',
            'fp_type': 'smd',
            'pads': self.pads.values(),
        }
        render_template(self.filename, FOOTPRINT_TEMPLATE, ctx)
